config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  get "up-db" => 'check#show'

  devise_for :users, controllers: { registrations: 'users/registrations',  omniauth_callbacks: 'users/omniauth_callbacks' }
  get "/king", to: "king_main#index"

  get '/(:user_id)', to: 'messages#index', as: "messages"
  post '/messages/(:user_id)', to: 'messages#create', as: "post_messages"
  get '/messages/:id/edit', to: 'messages#edit', as: 'edit_message'
  patch '/messages/:id', to: 'messages#update', as: "update_message"
  delete '/messages/:id', to: 'messages#destroy', as: "delete_message"
  get '/messages/:id/setread', to: 'messages#set_read', as: "read_message"
  root to: 'messages#index'


end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"

  validates :body, presence: true, length: { minimum: 1 }

  after_create_commit -> { broadcast_prepend_to(["sent_messages", sender_id, receiver_id], partial: 'messages/sent_message') }
  after_create_commit -> { broadcast_prepend_to(["received_messages", receiver_id, sender_id], partial: 'messages/received_message') }
  after_create_commit -> { broadcast_replace_to("users", target: "user_#{sender_id}", partial: 'king_main/user', locals: { user: sender, message: body }) }
  after_destroy_commit -> { broadcast_remove_to(["sent_messages", sender_id, receiver_id]) }
  after_destroy_commit -> { broadcast_remove_to(["received_messages", receiver_id, sender_id]) }
  after_update_commit -> { broadcast_replace_to(["sent_messages", sender_id, receiver_id], partial: 'messages/sent_message') }
  after_update_commit -> { broadcast_replace_to(["received_messages", receiver_id, sender_id], partial: 'messages/received_message') }

  before_update :set_edited

  after_create_commit do 
    receiver = self.receiver
    if !receiver.online && (receiver.last_mailed.nil? || receiver.last_mailed < Time.now - 1.minute) && receiver.receive_mail
       NotifyMailer.new_message(self.body, receiver, self.sender).deliver_now
       receiver.update(last_mailed: Time.now)
    end
  end
  private

  def set_edited 
    if body_changed? 
      self.edited = true
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	include Pagy::Backend
	before_action :authenticate_user!
	before_action :set_chat_user, only: %i[index create]
  before_action :set_message, only: %i[ edit update destroy set_read ]

  def index
		@pagy, @messages = pagy(Message.where(sender_id: current_user.id, receiver_id: @chat_user_id ).or(Message.where(receiver_id: current_user.id, sender_id: @chat_user_id)).order(id: :desc), items: 15)
    @message = Message.new(receiver_id: @chat_user)
  end

	def create
		@message = current_user.sent_messages.build(message_params)
		@message.receiver_id = @chat_user_id
	    respond_to do |format|
	      if @message.save
	      	format.turbo_stream 
	      	format.html { redirect_to messages_path(@chat_user_id)}
	        # format.json { render :index, status: :created, location: @messages }
	      else
	      	format.turbo_stream
	        format.html { render :index, status: :unprocessable_entity }
	        # format.json { render json: @task.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def edit

	end

	def update
		respond_to do |format|
      if @message.sender_id == current_user.id && @message.update(message_params)
      	format.turbo_stream()
        format.html { redirect_to messages_path }
        # format.json { render :index, status: :ok, location: @message }
      else
        format.html { render :index, status: :unprocessable_entity }
        # format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
		if @message.sender_id == current_user.id
			@message.destroy!
		end
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to messages_path }
      format.json { head :no_content }
    end
	end

	def set_read
		if @message.receiver_id == current_user.id
			@message.update(read: true)
		end
		respond_to do |format|
	    format.turbo_stream
      format.html { redirect_to messages_path }
      format.json { head :no_content }
    end
	end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def set_chat_user 
    	if current_user.id != 1 
    		@chat_user_id = 1
    	else
    		if params[:user_id]
    			@chat_user = User.find_by(id: params[:user_id])
    			@chat_user_id = params[:user_id].to_i
    		else
    			redirect_to king_path
    		end
    	end
    end

    def message_params
      params.require(:message).permit(:body)
    end

end

app/helpers/messages_helper.rb
module MessagesHelper
	include Pagy::Frontend
end

app/views/messages/_form.html.erb
<%= form_with(model: message, id: dom_id(message), url: post_messages_path(@chat_user_id), data: { controller: "form", action: "turbo:submit-end->form#reset"}) do |form| %>
    <div class=" flex gap-2 items-center  py-2 px-1 rounded">
      <%= form.text_area :body, rows: 1, placeholder: "Message Anirudha", data: {action: "form#resize keydown.enter->form#submit", form_target: "input"}, class: "block rounded-full outline-none bg-stone-900 px-3 py-2 w-full text-white max-h-52 resize-none", tabindex: "69" %>
      <button data-form-target="submitButton" type="submit" name="commit" class="rounded-full p-2 bg-primary text-stone-950 font-medium cursor-pointer" tabindex="69">
          <%= render "shared/svg/send" %>
    </div>
<% end %>

app/views/messages/_kingbar.html.erb
<div class="py-4 px-3 w-full border-b border-b-white flex justify-between items-center">
	<%= link_to "<h3 class='text-2xl'>Chat<span class='text-primary'>.anirudha</span></h3>".html_safe, root_path %>
	<div class="flex items-center gap-2">
		<span><%= @chat_user.username %></span>
		<%= render partial: "shared/status", locals: { status: @chat_user.online, user: @chat_user.id } %>
	</div>
</div>

app/views/messages/_message.html.erb
<% if message.sender_id != @chat_user_id %>
	<%= render partial: "messages/sent_message", locals: { message: message } %>
<% else %>
	<%= render partial: "messages/received_message", locals: { message: message } %>
<% end %>

app/views/messages/_received_message.html.erb
<%= turbo_frame_tag dom_id(message), class: "w-full flex flex-col" do %>
	<div class="self-start flex gap-2 items-center max-w-[75%]">
		<div class=" bg-stone-800 text-white px-4 pb-4 rounded-3xl rounded-bl self-start max-w-[100%]">
			<%= sanitize simple_format message.body, class: "hide-br break-words whitespace-break-spaces mt-4" %>
			<% if message.edited %><span class="text-[#71767b] text-sm">(edited)</span><% end %>
		</div>
	</div>
	<span class="text-[12px] text-[#71767b]"><%= local_time_ago(message.created_at) %></span>
	<% if !message.read %>
		<%= turbo_frame_tag "read_#{message.id}", src: read_message_path(message.id), class: "hidden" %>
	<% end %>
<% end %>

app/views/messages/_sent_message.html.erb
<%= turbo_frame_tag dom_id(message), data: {controller: "message", action: "focus->message#handleFocus keydown.esc->message#hidePopup"}, class: " flex flex-col items-end group/message", tabindex: "0" do %>
	<div data-message-target="innerDiv" class=" flex gap-2 items-center justify-end w-full">
		<div data-controller="popup" data-message-target="popup" data-action="keydown.esc->popup#hide">
			<div data-popup-target="target" data-action="click->popup#show" class="text-neutral-300 relative block md:hidden md:group-hover/message:block md:group-focus/message:block md:group-focus/message:border md:group-focus/message:border-white rounded-full  cursor-pointer p-1">
				<%= render "shared/svg/threedots" %>
			</div>
			<div data-popup-target="content" class="min-w-[8rem] p-1 flex-col gap-[2px] z-50 hidden absolute bg-stone-900 rounded -ml-16">
				<%= link_to edit_message_path(message), data: { popup_target: "firstBtn"}, class: "p-1 rounded hover:bg-[#4d748d] focus:bg-[#4d748d] flex items-center gap-2" do %>
					<%= render "shared/svg/edit" %>
					<span>Edit</span>
				<% end %>
				<%= button_to delete_message_path(message), method: :delete, class: " flex items-center gap-2 p-1 rounded hover:bg-red-500 focus:bg-red-500 w-full" do %>
					<%= render "shared/svg/delete" %>
					<span>Delete</span>
				<% end %>
			</div>
			 <div data-action="click->popup#hide" data-popup-target="overlay" class="fixed inset-0 w-full h-full bg-black opacity-50 z-40 hidden"></div>
		</div>
		<div data-message-target="contentDiv" class="bg-white text-black px-4 pb-4 rounded-3xl rounded-br max-w-[75%]">
			<%= sanitize simple_format message.body, class: "hide-br break-words whitespace-break-spaces mt-4" %>
			<% if message.edited %><span class="text-[#71767b] text-sm">(edited)</span><% end %>
		</div>
	</div>
	<div class="flex gap-1 items-center">
		<span class="text-[12px] text-[#71767b]"><%= local_time_ago(message.created_at) %></span>
		<%= render partial: "shared/svg/read", locals: { read: message.read } %>
	</div>
<% end %>

app/views/messages/edit.html.erb
<%= turbo_frame_tag dom_id(@message) do %>
	<%= form_with model:@message, url: update_message_path, class: "bg-white text-black p-4 rounded-3xl rounded-br flex flex-col", data: { controller: "form", action: "keydown.esc->form#close" } do |form| %>
		<%= form.text_area :body, rows: 1, data: {action: "form#resize keydown.enter->form#submit", form_target: "input"}, autofocus: true, class: "outline-0 border-0 focus:ring-0 resize-none" %>
		<div class="self-end flex gap-2 ">
			<%= link_to "Cancel", :back, data: { form_target: "closeBtn" }, class: "cursor-pointer py-2 px-3 border-2 border-black text-black rounded-lg" %>
			<%= form.submit "Update", data: {form_target: "submitButton"}, class: "cursor-pointer py-2 px-3 bg-[#95b3c7] rounded-lg text-black" %>
		</div>
	<% end %>
<% end %>

app/views/messages/index.html.erb
<main class="max-w-3xl mx-auto flex flex-col h-[100svh]">
	<% if current_user.id != 1 %>
		<%= render "shared/titlebar" %>
	<% else %>
		<%= render "kingbar" %>
	<% end %>
	<%= turbo_stream_from ["sent_messages", current_user.id, @chat_user_id] %>
	<%= turbo_stream_from ["received_messages", current_user.id, @chat_user_id] %>
	<div class="flex flex-col justify-between h-[calc(100svh-65px)]">
		<div class="flex flex-col-reverse overflow-y-auto px-1">
		    <%= turbo_frame_tag "messages", class: "flex flex-col-reverse gap-4 pt-1" do %>
		      	<%= render @messages %>
			      <% if @pagy.next %>
					    <%= turbo_frame_tag "messages", loading: :lazy, src: messages_path(@chat_user_id, @messages, page: @pagy.next), class: "flex flex-col-reverse gap-4" do %>
					 		<div class="w-full flex justify-center"><%= render "shared/svg/spinner" %></div>
					    <% end %>
			  		<% end %>
			<% end %>
		</div>
		<%= render "form", message: @message %>
	</div>
	<div id="userId" data-id="<%= current_user.id %>"></div>
</main>