config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  get "up-db" => 'check#show'

  devise_for :users, controllers: { registrations: 'users/registrations',  omniauth_callbacks: 'users/omniauth_callbacks' }
  get "/king", to: "king_main#index"

  get '/(:user_id)', to: 'messages#index', as: "messages"
  post '/messages/(:user_id)', to: 'messages#create', as: "post_messages"
  get '/messages/:id/edit', to: 'messages#edit', as: 'edit_message'
  patch '/messages/:id', to: 'messages#update', as: "update_message"
  delete '/messages/:id', to: 'messages#destroy', as: "delete_message"
  get '/messages/:id/setread', to: 'messages#set_read', as: "read_message"
  root to: 'messages#index'


end

app/controllers/king_main_controller.rb
class KingMainController < ApplicationController
  before_action :authenticate_user!
  def index
  	if current_user.id != 1 
  		redirect_to root_path, alert: "You are no king"
  	end
  	@users = User.where.not(id: 1).where.not(confirmed_at: nil).order(last_seen: :desc)
  end
end

app/views/king_main/_user.html.erb
<%= turbo_frame_tag dom_id(user) do %>
	<%= link_to messages_path(user), data: { turbo_frame: "_top"} do %>
		<div class="w-full py-4 px-4 bg-stone-900 rounded flex items-center justify-between">
			<div class="w-[90%]">
				<div class="flex gap-2 items-center">
					<h2 class="text-2xl"><%= user.username %></h2>
					<span class="text-sm">last seen <%= local_time_ago(user.last_seen) %></span>
					<%= render partial: "shared/status", locals: { status: user.online, user: user.id } %>
				</div>
				<span class="text-sm break-words"><%= ((user.sent_messages + user.received_messages).max_by{ |message| message.created_at})&.body %></span>
			</div>
			<div class="text-black bg-primary rounded-full w-8 h-8 grid items-center text-center">
				<%= user.sent_messages.where(read: false).count %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/king_main/index.html.erb
<main class="max-w-3xl mx-auto flex flex-col h-[100svh]">
	<%= render "shared/titlebar" %>
		<%= turbo_stream_from "users" %>
		<%= turbo_frame_tag "users", class: "flex flex-col gap-2 px-2 pt-1" do %>
			<%= render partial: "king_main/user", collection: @users, locals: { user: :user, message: nil } %>
		<% end %>
</main>